# Setup
title:               Masters Thesis
tagline:             '2364784W'
description:         'A website for displaying results from my masters thesis'
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              2364784W
  url:               www.github.com/2364784w
  email:             2364784w@student.gla.ac.uk

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
