# Setup
title:               Econophysics - Agent-based modelling of markets from kinetic theory of gases and Brownian motion
tagline:             'Leon Williams'
description:         'A webpage depicting results from my Master's Thesis'
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Leon Williams
  url:               www.github.com/leonbaiyu
  email:             leonbaiyu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
