# Setup
title:               Econophysics
tagline:             'Leon Williams'
description:         'A website for displaying results from my master's thesis'
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Leon Williams
  url:               www.github.com/leonbaiyu
  email:             leonbaiyu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
